# Generated by Django 2.0.6 on 2018-06-27 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe ingresarse en el formato: '7751234567'. Hasta 10 dígitos permitidos.", regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='address',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='client',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
