# Generated by Django 2.0.6 on 2018-06-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20180627_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('no_scheck', models.BooleanField(default=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='income.Cliente')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
