# Generated by Django 2.0.6 on 2018-06-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='no_scheck',
            new_name='income_check',
        ),
        migrations.AddField(
            model_name='income',
            name='no_icheck',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
