# Generated by Django 2.0.6 on 2018-07-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_cliente_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
